# Generated by Django 5.1.1 on 2024-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(default='event', max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('note', models.CharField(default='memo', max_length=50)),
                ('location', models.CharField(default='loca', max_length=50)),
                ('person', models.CharField(default='some', max_length=50)),
            ],
        ),
    ]
