# Generated by Django 5.1.1 on 2024-10-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasemgnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.RemoveField(
            model_name='events',
            name='person',
        ),
    ]
